actor_learning_rate: 5.0e-05
alpha_reward: 100.0
batch_size: 128
beta_reward: 1.25
critic_learning_rate: 5.0e-05
episode_simulation_days: 365
eprice_ahead: 0
epsilon: 0.3
gamma: 0.98
gamma_reward: 1.25
initial_replay_buffer_size: 1500000
nn_features1: 350
nn_features2: 350
ou_enable: true
ou_mu: 0.0
ou_sigma: 0.2
ou_theta: 0.15
pv_panels_number: 10.0
replay_buffer_size: 1500000
test_iterations: 5
test_name: Test_145
