actor_learning_rate: 5.0e-05
alpha_reward: 100.0
batch_size: 128
beta_reward: 3.0
critic_learning_rate: 0.0001
episode_simulation_days: 365
eprice_ahead: 2
epsilon: 0.3
gamma: 0.98
gamma_reward: 1.5
initial_replay_buffer_size: 1500000
light_ctrl: false
nn_features1: 400
nn_features2: 350
ou_enable: true
ou_mu: 0.0
ou_sigma: 0.4
ou_theta: 0.2
pv_panels_number: 10.0
replay_buffer_size: 1500000
test_iterations: 5
test_name: Test_183
