test_name: "Test_154"
light_ctrl: false
test_iterations: 5
actor_learning_rate: 0.00005
critic_learning_rate: 0.0001
gamma: 0.98
replay_buffer_size: 1500000
initial_replay_buffer_size: 1500000
batch_size: 128
ou_enable: True
ou_theta: 0.15
ou_sigma: 0.2
ou_mu: 0.0
epsilon: 0.3
nn_features1: 350
nn_features2: 350
episode_simulation_days: 365
pv_panels_number: 10.0
alpha_reward: 100.0
beta_reward: 4.0
gamma_reward: 5.0
eprice_ahead: 0